name: command
services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: commander
    command: 
      - /usr/bin/bash
      - -c
      - |-
        echo 'compose commnad.'
        bash
    tty: true



