name: entrypoint
services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: entrypoint
    entrypoint:
      - /usr/bin/bash
      - -c
      - |-
        echo 'compose entrypoint.'
        bash
    tty: true



